#Misc outfit startingGear definitions.
#Rename MobAghostGear to MobAghostGearOld in misc_startinggear.yml in Resources\Prototypes\Roles\Jobs\Fun to use!

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelAdmin
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal
    - Multitool
    - PowerDrill
    - SprayPainterBorg