- type: job
  id: CaptainUber
  name: job-name-captain-uber
  description: job-description-captain-uber
  playTimeTracker: JobCaptainUber
  requirement:
    !type:RoleTimeRequirement
    role: JobCaptain
    time: 40h
  weight: 20
  startingGear: CaptainUberGear
  icon: "JobIconCaptainUber"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: true
  accessGroups:
  - AllAccess
  access:
  - CaptainUber
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainUberGear
  equipment:
    shoes: ClothingShoesBootsSpeed
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    gloves: ClothingHandsGlovesCaptain
    id: CaptainUberPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltChiefEngineerFilled
    suitstorage: JetpackUltraCaptainUberFilled
    pocket1: PowerCellMicroreactor
    pocket2: GasAnalyzer
  storage:
    back:
    - HandheldHealthAnalyzer
    - NodeScanner
    - HandHeldMassScanner
    - MineralScanner
    - ForensicScanner
    - ClothingEyesGlassesThermal
    - SprayPainterBorg
    - UniversalIDCard
    - CaptainIDCard
    - CaptainIDCard
    - CaptainIDCard
    - CaptainIDCard
    - ClothingShoesBootsLaceup
    - DrinkFlask
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainUberChameleonOutfit
  job: CaptainUber
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
